.\" Manpage for shellnotes-clearlogs(hidden).
.\" Contact dmarakom@gmail.com to correct errors or typos.

.TH clearlogs 1
.SH NAME

clearlogs \- clear every shellnotes logfile in your system.

.SH SYNOPSIS
.PP
.B clearlogs

.SH DESCRIPTION

.B clearlogs
Wipes out all the text from every singe logfile stored in .shellnotes/logs/ . This command MUST NOT be used, unless necessary. It won't have an affect on your Notes or on shellnotes' performance.


.SH AUTHOR

Dimitris Marakomihelakis (dmarakom@gmail.com)
