.\" Manpage for shellnotes-findmisplacednote.
.\" Contact dmarakom@gmail.com to correct errors or typos.

.TH findmisplacednote 1
.SH NAME

shellnotes-findmisplacednote \- Find a note missing from your notes folder.

.SH SYNOPSIS
.PP
.B findmisplacednote
.IR [FILE...]

.SH DESCRIPTION

.B findmisplacednote
uses find (do "man find") to check if a note exists in the user's system. 
This command must be run only when findnote (do "man findnote") doesn't result in an existing note.

.\".SH OPTIONS

.\".SH BUGS

.\".TP
.\".BR \Withoutstringbug ", " \-wsBug ", " \72
.\"If there are no matches in the input, "notegrep -ws" will display the file as is.

.SH AUTHOR

Dimitris Marakomihelakis (dmarakom@gmail.com)
