.\" Manpage for findnote
.\" Contact dmarakom@gmail.com to correct errors or typos.
.TH man 8 "30/12/2020" "" "findnote man page"
.SH NAME
shellnotes-findnote \- Find a note in your notes folder.
.SH SYNOPSIS
findnote [FILENAME]
.SH DESCRIPTION
findnote() checks if a note exists in your notes folder.
.SH OPTIONS
[FILENAME] \- The name of the note.
leave a blank parameter ("findnote") and shellnotes will ask you for the filename with an input.
.SH BUGS
No known bugs.
.SH AUTHOR
Dimitris Marakomihelakis (dmarakom@gmail.com)