.\" Manpage for shellnotes-listnotes.
.\" Contact dmarakom@gmail.com to correct errors or typos.

.TH listnotes 1
.SH NAME

shellnotes-listnotes \- list your notes from wherever you are.

.SH SYNOPSIS
.PP
.B listnotes
[\fIOPTION\fR]

.SH DESCRIPTION

.B listnotes
uses ls (do "man ls") to list all your notes in different ways.


.SH OPTIONS

.TP
.BR \-d ", " \--dynamic
Dynamic view of all your notes and their content.  

.TP
.BR \-n ", " \--number
Count the number of notes in your notes folder.

.TP
.BR \-f ", " \--folder
Show the current default notes folder.

.TP
.BR \-v ", " \--view
View notes one by one using the 'less' command. Press 'Q' to move from one note to the other and scroll with your mouse or arrow keys.

.SH BUGS

.TP
None known (as of Aug 13, 2023)
.SH AUTHOR

Dimitris Marakomihelakis (dmarakom@gmail.com)
