.\" Manpage for shellnotes-listnotes.
.\" Contact dmarakom@gmail.com to correct errors or typos.

.TH listnotes 1
.SH NAME

shellnotes-listnotes \- list your notes from wherever you are.

.SH SYNOPSIS
.PP
.B listnotes
[\fIOPTION\fR]

.SH DESCRIPTION

.B listnotes
uses ls (do "man ls") to list all your notes in different ways.


.SH OPTIONS

.TP
.BR \-d ", " \--dynamic
Dynamic view of all your notes and their content.  

.TP
.BR \-n ", " \--number
Count the number of notes in your notes folder.

.TP
.BR \-f ", " \--folder
Show the current default notes folder.

.SH BUGS

.TP
.BR \-DynamicOutputBug ", " \-dOutBug ", " \116
.PP
listnotes -d output generates autoscroll, instead of starting from where the command was executed.

.SH AUTHOR

Dimitris Marakomihelakis (dmarakom@gmail.com)
