.\" Manpage for newnote
.\" Contact dmarakom@gmail.com to correct errors or typos.
.TH man 8 "30/12/2020" "" "newnote man page"
.SH NAME
shellnotes-newnote \- Write a new note using your text editor.
.SH SYNOPSIS
newnote [FILENAME]
.SH DESCRIPTION
newnote() uses your default text-editor to write a new note and saves it into your notes folder when finished.
.SH OPTIONS
[FILENAME] \- The name of the new note.
leave a blank parameter ("newnote") and shellnotes will ask you for the filename with an input.
.SH BUGS
If the default editor for newnote() is not valid, the program is likely to crash.
.SH AUTHOR
Dimitris Marakomihelakis (dmarakom@gmail.com)