.\" Manpage for shellnotes-notewc.
.\" Contact dmarakom@gmail.com to correct errors or typos.

.TH notewc 1
.SH NAME

shellnotes-notewc \- get info about a note.

.SH SYNOPSIS
.PP
.B notewc
.IR [FILE...]

.SH DESCRIPTION

.B notewc
uses wc (do "man wc") to show lines, words, chars and name of a note.


.\".SH OPTIONS

.\".SH BUGS

.SH AUTHOR

Dimitris Marakomihelakis (dmarakom@gmail.com)

