.\" Manpage for shellnotes-quicknote.
.\" Contact dmarakom@gmail.com to correct errors or typos.

.TH quicknote 1
.SH NAME

shellnotes-quicknote \- write a new note directly via terminal.

.SH SYNOPSIS
.PP
.B quicknote
.IR [FILE...]

.SH DESCRIPTION

.B quicknote
uses your in-terminal text-editor to write a new note and saves it into your notes folder when finished.
It works well with the nano editor.


.SH AUTHOR

Dimitris Marakomihelakis (dmarakom@gmail.com)

