.\" Manpage for quickread.
.\" Contact dmarakom@gmail.com to correct errors or typos.

.TH quickread 1
.SH NAME

shellnotes-quickread \- Read new note directly in your terminal.

.SH SYNOPSIS
.PP
.B notegrep
[\fIOPTION\fR]
.IR [FILE...]

.SH DESCRIPTION

.B quickread
uses cat (do "man cat") to view a note. It only runs inside your notes folder.

.SH OPTIONS

.TP
.BR \-l ", " \--line =\fIINT\fR
Display a specific line of a note.

.TP
.BR \-r ", " \--reverse =\fISTRING\fR
Reverse output of cat, using tac.

.TP
.BR \-s ", " \--sort =\fISTRING\fR
Print output piped to the sort command.

.SH BUGS

.TP
.BR \-FloatBug ", " \-fBug ", " \102
If $line is a float, sed returns en error message.

.SH AUTHOR

Dimitris Marakomihelakis (dmarakom@gmail.com)
