.\" Manpage for readnote.
.\" Contact dmarakom@gmail.com to correct errors or typos.
.TH man 8 "30/12/2020" "" "readnote man page"
.SH NAME
shellnotes-readnote \- Read a note using your text editor.
.SH SYNOPSIS
readnote [FILENAME]
.SH DESCRIPTION
readnote() uses your default text-editor to read a note.
.SH OPTIONS
[FILENAME] \- The name of the note.
leave a blank parameter ("readnote") and shellnotes will ask you for the filename with an input.
.SH BUGS
If the default editor for readnote() is not valid, the program is likely to crash.
.SH AUTHOR
Dimitris Marakomihelakis (dmarakom@gmail.com)