.\" Manpage for shellnotes-rmdups.sh.
.\" Contact dmarakom@gmail.com to correct errors or typos.

.TH rmdups 1
.SH NAME

shellnotes-rmdups.sh \- remove duplicate lines from a note

.SH SYNOPSIS
.PP
.B rmdups
[\fIOPTION\fR]
[\fINOTENAME\fR]

.SH DESCRIPTION

.B rmdups
removes duplicate lines from a note.

.SH ARGUMENTS

.TP
.BR \fINOTENAME\fR
Name of the note to remove duplicate lines from.

.SH USAGE

Remove duplicate lines from a note:
.PP
.B rmdups
[\fINOTENAME\fR]

.SH AUTHOR

Dimitris Marakomihelakis (dmarakom@gmail.com)

.SH NOTES

None.

.SH BUGS

None known.

.SH EXAMPLES

Remove duplicate lines from a note named "my_note":
.PP
.B rmdups
my_note

.SH FILES

Notes are stored in the default notes folder.

.SH ENVIRONMENT

Default notes folder can be set using the \fBDEFAULT_PATH\fR environment variable.

.SH HISTORY

The \fBrmdups\fR command was introduced in version 4.0 of the shellnotes utility.

.SH BUG REPORTS

Please report bugs to dmarakom@gmail.com.

.SH COPYRIGHT

This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
