.\" Manpage for shellnotes.
.\" Contact dmarakom@gmail.com to correct errors or typos.
.TH man 8 "30/12/2020" "" "shellnotes man page"
.SH NAME
shellnotes \- An easy, simple and fast way to keep notes directly via terminal. 
.SH SYNOPSIS
shellnotes [OPTION]
.SH DESCRIPTION
Shellnotes is a note system for advanced linux and terminal users. It is made out of a lot of other commands and scripts, so if you want to get information and help for every single one of them, you should visit the Help Page (~/.shellnotes/docs/help manually, or type shellnotes --help in the terminal).
.SH OPTIONS
-u or --update \- Update shellnotes.
-v or --version \- Display the current version.
-h or --help \- Display help from the Help Page.
-r \- View the github repository of the program.
-sd or --set-defaults \- Set default editors and folder for writing and storing your notes.
-au or --auto-update \- Toggle the auto-update feature.
-l or --logs \- Open a logfile.
leave a blank parameter ("shellnotes") for checking if shellnotes is installed correctly.
.SH BUGS
No known bugs.
.SH AUTHOR
Dimitris Marakomihelakis (dmarakom@gmail.com)